### ISSUE TITLE
Please include a license for this project

### ISSUE THREAD

**Issue by TTWNO** [shotazc/pinyin2epub#1]
Hello, please include a license for this project so others can copy, modify, distribute, etc... your code.

I am wanting to use this for a project, but without a license, it's difficult to know what might come of me if I use it 😆

Thanks much!

This website is in English, but it should help with selecting an appropriate license: https://choosealicense.com/

**Comment by shotazc** [comment]
You can use this code if you follow MIT license. 
Thank you.

**Comment by TTWNO** [comment]
Thank you!
